export const Levels = [
  {
    coefficient: 1,
    countChar: 2,
    variousSymbols: 3,
    time: 3,
    maxScore: 30,
  },
  {
    coefficient: 1.1,
    countChar: 2,
    variousSymbols: 3,
    time: 2.9,
    maxScore: 60,
  },
  {
    coefficient: 1.2,
    countChar: 2,
    variousSymbols: 4,
    time: 2.9,
    maxScore: 90,
  },
  {
    coefficient: 1.3,
    countChar: 2,
    variousSymbols: 5,
    time: 2.9,
    maxScore: 120,
  },
  {
    coefficient: 1.4,
    countChar: 3,
    variousSymbols: 5,
    time: 2.9,
    maxScore: 160,
  },
  {
    coefficient: 1.5,
    countChar: 3,
    variousSymbols: 6,
    time: 2.8,
    maxScore: 200,
  },
  {
    coefficient: 1.6,
    countChar: 3,
    variousSymbols: 7,
    time: 2.8,
    maxScore: 250,
  },
  {
    coefficient: 1.7,
    countChar: 4,
    variousSymbols: 7,
    time: 2.8,
    maxScore: 320,
  },
  {
    coefficient: 1.8,
    countChar: 4,
    variousSymbols: 8,
    time: 2.7,
    maxScore: 400,
  },
  {
    coefficient: 1.9,
    countChar: 4,
    variousSymbols: 9,
    time: 2.7,
    maxScore: 500,
  },
  {
    coefficient: 2,
    countChar: 5,
    variousSymbols: 9,
    time: 2.6,
    maxScore: 1000,
  },
  {
    coefficient: 2.1,
    countChar: 5,
    variousSymbols: 10,
    time: 2.6,
    maxScore: 3000,
  },
  {
    coefficient: 2.2,
    countChar: 5,
    variousSymbols: 11,
    time: 2.5,
    maxScore: 6000,
  },
  {
    coefficient: 2.3,
    countChar: 6,
    variousSymbols: 11,
    time: 2.5,
    maxScore: 8000,
  },
  {
    coefficient: 2.4,
    countChar: 6,
    variousSymbols: 12,
    time: 2.4,
    maxScore: 10000,
  },
  {
    coefficient: 2.5,
    countChar: 6,
    variousSymbols: 12,
    time: 2.4,
    maxScore: 12000,
  },
  {
    coefficient: 2.6,
    countChar: 7,
    variousSymbols: 12,
    time: 2.3,
    maxScore: 14000,
  },
  {
    coefficient: 2.7,
    countChar: 7,
    variousSymbols: 12,
    time: 2.2,
    maxScore: 16000,
  },
  {
    coefficient: 2.8,
    countChar: 7,
    variousSymbols: 12,
    time: 2.1,
    maxScore: 18000,
  },
  {
    coefficient: 2.9,
    countChar: 7,
    variousSymbols: 12,
    time: 2,
  },
];
